### ISSUE TITLE
Can valtio replace jotai completely?

### ISSUE THREAD

**Issue by naivefun** [pmndrs/valtio#141]
Honestly valtio feels so simple but great, but I'm not sure if there are any drawbacks by choosing this over jotai or recoil. Is there any need-to-know before I decide to drop other state managers?

**Comment by dai-shi** [comment]
Apart from stylistic difference, one the most important notes is: jotai/recoil states reside in react, whereas valtio/zustand states stay outside react. How does it make difference? Honestly, I don't know yet. My hope was to support "state branching" in jotai, which turned out to be impossible. I'm not familiar with recoil implementation, so not sure how it does. We will revisit this once new React with concurrent mode lands. Also, react may expose a new feature to support branching for module state. we don't know the future.

Another point is valtio/zustand states become a bit tricky in ssr scenario.

Hope it helps.

**Comment by naivefun** [comment]
Great to know. Can you elaborate on SSR problem?

**Comment by dai-shi** [comment]
As far as I learned in https://github.com/pmndrs/zustand/issues/182, the module state is shared among sessions. So, you need to do something to isolate it. If your app is something totally consistent across sessions, it might not be an issue.

**Comment by dai-shi** [comment]
Another thing to note is: module state fits well for data centric apps (react as a library), react state fits well for react centric apps (react as a framework?).

**Comment by naivefun** [comment]
Thanks!

**Comment by zcaudate** [comment]
I found this issue when doing a search of how popular valtio is

https://www.npmtrends.com/easy-peasy-vs-jotai-vs-valtio-vs-zustand

I really think it should be more popular but I think it's funny how saturated react is with redux and how influential it is.

https://www.npmtrends.com/jotai-vs-recoil-vs-redux-vs-valtio-vs-zustand


----

You can construct a matrix of atom-base/state-machine-base and in-react/outside-react libs

<img width="424" alt="Screen Shot 2021-08-03 at 1 38 41 am" src="https://user-images.githubusercontent.com/1455572/127901877-d0d7f81f-8485-4292-a686-98e839897a5f.png">

-----

I haven't been doing frontend development very long so when I started with react - here is my progression of stores

- started trying to use redux
- I looked at zustand
- Then implemented my own store based on `useContext` and a version of `useGlobalState`
- Then found out about jotai and recoil
- Then found out about valtio but did not seriously consider it.
- Experimented using a combination of xstate with jotai
- Used a combination of jotai and valtio stores.
- Refactored to use exclusively valtio.

------

So I was big on jotai for a while until I started sprinkling valtio in my app. And then I just continued to sprinkle valtio until it was obvious that I didn't even need jotai anymore.

For me, the biggest advantage of valtio is the ability to quickly inspect state. When an app is small and state can be contained, then it really doesn't matter what library to use.

When an app gets more features, then the most difficult part is the ability to control state.

When state in managed by react, the smallest unit of functionality is the Component. In order to do anything, you have to go through the react lifecycle. Even something as simple as incrementing a field requires a StoreProvider and a hook. The in-react state solutions always have to rely on tooling and as far as I'm concerned, the only library with tooling out there is redux. However, redux tooling is complicated, it doesn't work half the time and redux itself has a lot of issues.

----

When state is managed outside of react, the smallest unit of functionality is a function. It also decouples the display of the data from the manipulation of that data. So I can write functions to manipulate data without worrying about going through the react lifecycle. This is a huge advantage because it makes for better code. With valtio, when there is a need to display data within a state, it just works.

When my app got to a certain size, I decided to start initialising proxies as global variables. It might sound like a bad idea but global state makes it trivial for inspecting and manipulating state and eliminates the need for tooling to change state. It's great and super easy to build out functionality.

----

One reason I didn't consider zustand was that redux was such a horrible experience that I just avoided anything that remotely reminded me of it - but I'm sure it's great and being an outside-react solution, it would have the same properties as valtio.

**Comment by AjaxSolutions** [comment]
>>> redux was such a horrible experience

Popularity of redux as been declining for the [past 4 years](https://2020.stateofjs.com/en-US/technologies/datalayer/).

**Comment by zcaudate** [comment]
Usage isn't though.

![thumbs_b_c_341dd448c6b122f26983fdbda5ae0dd5](https://user-images.githubusercontent.com/1455572/127941178-4fc49545-fc53-439e-bc19-93d3861d6935.jpg)

I'm betting it's because of redux tooling.

**Comment by zcaudate** [comment]
Usage isn't though

<img width="840" alt="Screen Shot 2021-08-03 at 8 57 37 am" src="https://user-images.githubusercontent.com/1455572/127941268-56336a5a-9e3a-4112-82c4-a09d1886a170.png">

I'm betting it's because of redux tooling.

**Comment by Andarius** [comment]
>     * started trying to use redux
>     * I looked at zustand
>     * Then implemented my own store based on `useContext` and a version of `useGlobalState`
>     * Then found out about jotai and recoil
>     * Then found out about valtio but did not seriously consider it.
>     * Experimented using a combination of xstate with jotai
>     * Used a combination of jotai and valtio stores.
>     * Refactored to use exclusively valtio.

I'm currently following a similar path:
 - did redux / redux saga for 2 years
 - tried zustand as a POC but it does not quite fit my need (https://github.com/pmndrs/zustand/issues/520#issuecomment-891087525)
 - currently in the process of replacing my zustand POC with valtio

**Comment by zcaudate** [comment]
> separate state from actions

Yeah. Most of the redux-like libraries are modelled based on an immutable store and actions manipulating that store (state machine). When you design like that, you basically always have to do a top-down approach because every action can potentially affect everything else in a given store. People will argue that stricter is better but apps are more complicated than traffic lights and  it's really easy to get stuck in a corner with the top-down approach because refactoring gets really painful.

**Comment by zcaudate** [comment]
plus. react itself is already has state-machine like qualities to it so it doesn't make sense to put another state machine controller on top of it.

It actually needs a better eventing model - which is what valtio provides.

**Comment by 205g0** [comment]
@zcaudate thanks for your nice comparison post, super helpful!

@dai-shi thanks for building all this great libs! I settled for valtio for similar reasons as zcaudate. I just realized that you are still pretty active maintaining jotai. So, I am wondering if all your libs will be maintained in let's say 2, 3 or 5 years. Because changing the state management in my current (bigger) app could be quite some work and I'd like to invest time and money into your favorite lib, so I could at least minimize the risk of a future refactor.

**Comment by dai-shi** [comment]
Hi, thanks for your comment and choosing valtio.
I see your concern. Technically speaking, it's OSS.
But, I guess your question is comparing with other libraries. So, here's my perspective. jotai is more active because it's less stable and more feature rich. valtio, on the other hand, is more feature complete, and thus less active. zustand is much more complete.
As you see #234, I'm actively maintaining this repo too. It's small enough for myself to maintain.
jotai is bigger, and requires more contributors to maintain.
btw, I have another library [react-tracked](https://github.com/dai-shi/react-trackd) which I will maintain like others. valtio and react-tracked use the same internal library, which will also be maintained.
That said, I can't predict what will happen in 5 years.

**Comment by dsacramone** [comment]
> > ```
> > * started trying to use redux
> > * I looked at zustand
> > * Then implemented my own store based on `useContext` and a version of `useGlobalState`
> > * Then found out about jotai and recoil
> > * Then found out about valtio but did not seriously consider it.
> > * Experimented using a combination of xstate with jotai
> > * Used a combination of jotai and valtio stores.
> > * Refactored to use exclusively valtio.
> > ```
> 
> I'm currently following a similar path:
> 
> * did redux / redux saga for 2 years
> * tried zustand as a POC but it does not quite fit my need ([[Question] Separate state from actions zustand#520 (comment)](https://github.com/pmndrs/zustand/issues/520#issuecomment-891087525))
> * currently in the process of replacing my zustand POC with valtio as it seems to fit my mental model of state / actions
> 
> Also I'm using React Native and since Proxy is available since 0.64 (recent) with Hermes, I want to give it a try. It might bring new people to this library too.

Since its been a few months,  I am curious your thoughts on Valtio. Also, I am curious how you solved the issue that led you to drop Zustand, with Valtio?

**Comment by zcaudate** [comment]
@dsacramone: I really recommend it.

**Comment by dsacramone** [comment]
> @dsacramone: I really recommend it.
Did you solve this issue: https://github.com/zcaudate/js-blessed.store-test, in your github?

**Comment by zcaudate** [comment]
@dsacramone: this is an issue with the blessed renderer, not valtio. However, I would actually recommend avoiding  suspense altogether, and setting a 'pending' flag on valtio to trigger state switches. It's a safer method.

**Comment by Andarius** [comment]
@dsacramone I really like the simplicity of Valtio. There are some gotchas but overall it works like a charm.

Regarding Zustand and Valtio, I now write my "store" like this:

```
export namespace TrainingSessionStore {
    export const state = proxy<ISessionState>(initialState())

    export const resetState = () => setAllKeys(initialState(), state)

    export const loadSession = async (
        sessionID: string,
        options: { setStore: boolean } | undefined = { setStore: true }
    ) => {
        const lang = await getLang()
        const { resp, error } = await Requests.get(URLS.session, {
            params: { id: sessionID, lang }
        })
        if (resp) {
            const session = convertSession(resp)
            if (options.setStore) state.session = session
            return { success: { session } }
        }
        return { error }
    }

    export const resetSession = () => {
        state.samples = undefined
        state.session = undefined
    }
   ```

**Comment by naivefun** [comment]
What I like valtio most is that it works both inside and outside of React.. Just like what @Andarius shows sometimes the app is not only UI driven but also driven by server data push. In large project the data service is usually separated from UI component and a `fetch` inside hooks is not really a good option.

Strictly Redux is still the best one in terms of 'React style', both of them follows immutable and one way data flow. But state management can become so complex that we need something easier, which is also why mbox is so popular. In practice we use valtio together with immer to get benefits from both ideas, works fine so far.

**Comment by dsacramone** [comment]
> * [Question] Separate state from actions zustand#520 (comment)

If I may ask @Andarius , how large is your team - that uses Valtio? My team is decent size and I worry about introducing proxy based state management and the gotchas that go with that. The ability to mutate anywhere being proxy based, we could end up with dom nodes in the state etc... I am just curious the amount of teammantes and size of the project - because I am leaning to keeping zustand because there is an implied usage (even though its unopiniated) that is safer for larger teams/feature.

**Comment by Andarius** [comment]
We are only 2 using valtio for now.
If you have good testing, you catch the issues early and did most of the work trying to understand the pitfalls in the first place so there is that.
Regarding the size of the project it's only a React Native app.

**Comment by 205g0** [comment]
> valtio together with immer 

why immer? do you have some good example/use cases on why immer is a must-have with valtio?

**Comment by CharlieDigital** [comment]
@dsacramone 

> The ability to mutate anywhere being proxy based, we could end up with dom nodes in the state

I see this come up a lot and I wonder in what use case would anyone **ever** put a DOM node into state?

I don't understand the origin of this hypothetical pitfall.  Wouldn't one mutate the state that would then mutate the target node?

**Comment by DennisSmolek** [comment]
> @dsacramone
> 
> > The ability to mutate anywhere being proxy based, we could end up with dom nodes in the state
> 
> I see this come up a lot in discussions around Valtio (Reddit threads) and I wonder in what use case would anyone **ever** put a DOM node into state?
> 

Look at this [**OFFICIAL** R3F example](https://codesandbox.io/s/ground-reflections-and-video-textures-bfplr?file=/src/App.js:420-561)(Line 13)

The I [did the same thing ](https://codesandbox.io/s/leva-custom-video-plugin-demo-d0rct?file=/src/LevaVideoPlugin/index.js)
but worse by injecting it into ANOTHER sate while playing with the Leva plugin API.

I'm passing the VIDEO element (DOM node) as a state value

And to be honest... This is the RIGHT thing to do.


However, I think the reference is hyperbole.. Meaning that things will get so crazy/out of wack that without the inherent super strict nature of [Insert Platform Here] the team will get messy
