### ISSUE TITLE
Race condition when using addComputed with a Promise based return object

### ISSUE THREAD

**Issue by curtisy1** [pmndrs/valtio#170]
New valtio user here, so I might be on the wrong track but I stumbled upon something I cannot quite pin down yet.

I'm trying to use valtio together with [class-validator](https://github.com/typestack/class-validator) to validate user input on the fly. For that I am (ab)using a computed value called errors that needs to run async (due to some of the validations requiring backend calls).

Simplified, the code boils down to what can be seen in [this hacked together codesandbox example](https://codesandbox.io/s/valtio-simple-counter-forked-6upu4).

However this doesn't seem to work. In this sandbox, React is actually telling me about adding `<Suspense fallback=...>` which is already there. When running this locally, it seems to throw after trying to call `setState` in [useMutableSource](https://github.com/pmndrs/valtio/blob/master/src/useMutableSource.ts#L97) telling me setState was called on an unmounted component.

My uneducated guess was that it had something to do with the Promise object being set as the new value [here](https://github.com/pmndrs/valtio/blob/master/src/utils.ts#L191) so I changed it to only assign non Promise values directly:
```
if (value instanceof Promise) {
  ...
} else {
  targetObject[key] = value
}
```

Which seems to work fine. However I'm not quite sure if this is the correct approach or the issue itself is something entirely different, so I'm wondering whether assigning the Promise is expected behavior or I stumbled upon a bug?

**Comment by dai-shi** [comment]
Hey, nice try. I'd say the combination of computed and suspense is not well tested.
I tried your fix, but it makes a test to fail. There should be some other correct ways.

Looking at your codesandbox, it's a bit complicated and hard to track down.
Would you be able to create a codesandbox as minimal as possible? No 3rd-party libs.
So that we can create a test case. Or, you can directly create a test case.

**Comment by curtisy1** [comment]
Hey Daishi, thanks for the quick reply! I've updated the codesandbox to a bare minimum so that the issue can still be reproduced.

**Comment by dai-shi** [comment]
Thanks for the minimal codesandbox!
It turns out that the issue is about having Suspense inside.

https://codesandbox.io/s/valtio-simple-counter-forked-g96m7?file=/src/App.tsx

This fixes it. This is because `useSnapshot` suspends. Note this is not related with addComputed, or even valtio, but with any hooks that suspend.

**Comment by curtisy1** [comment]
Yep, this indeed fixes it. Thank you!
