### ISSUE TITLE
subscribe callback not being invoked when changing object

### ISSUE THREAD

**Issue by water-a** [pmndrs/valtio#241]
```ts
import { proxy, subscribe } from 'valtio/vanilla';
const state = proxy({ arr: ["1"] });
subscribe(state.arr, () => {
  console.log("arr changed to:", state.arr);
});
state.arr = [];
```

Expected behavior: subscribe callback is called
Current behavior: subscribe callback is not called when the underly object is changed

**Comment by dai-shi** [comment]
Yeah, this is sometimes reported. It would be nice if we could improve docs.

Basically, what you are doing is the same as this:
```js
let arr = proxy(["1"]);
subscribe(arr, () => {
  console.log("arr changed to:", state.arr);
});
arr = proxy([]);
```
☝️ It doesn't work because it's a new reference.

`state.arr = []` is mutating "state", so you need to `subscribe(state, ...)`. Alternatively, `subscribeKey` may or may not work.

**Comment by dai-shi** [comment]
btw, another solution I recommend is to clear an array with mutating itself.
```js
state.arr.splice(0);
```
