### ISSUE TITLE
Cannot build a Valtio Proxy from any other Proxy object

### ISSUE THREAD

**Issue by benjamind** [pmndrs/valtio#275]
Currently the lib doesn't appear to support making a Valtio proxy over an existing (non-Valtio) proxy object.

This makes interop with other libs somewhat tricky, specifically libraries like [BufferBackedObject](https://github.com/GoogleChromeLabs/buffer-backed-object) which create proxies over an abstract data view to write data into typed array buffers. Right now I can't make a Valtio proxy over these BufferBackedObjects without making an intermediate object to write through the BBO.

**Comment by dai-shi** [comment]
Valtio basically supports plain objects (and arrays) by design, so complex objects like BufferBackedObject are not wrapped or you want to use `ref()` to explicitly avoid wrapping by valtio.

That said, creating a valtio proxy from other proxy would be nice. I think it could work. Not sure about BBO, but a plain proxy object `new Proxy({}, {})` could.
So the questions are:
a) if valtio can work with plain proxy objects, and
b) if valtio can work with BBO specifically.

https://codesandbox.io/s/mystifying-ully-pcbmn?file=/src/App.js This is for b). Looks like working so far?

**Comment by benjamind** [comment]
Interesting. When I tried similar in my app this afternoon I ended up getting an error related to accessing the LISTENERS set via the symbol on the bbo proxy object which from my read was valtio assuming the proxy was a valtio proxy. I should try again in a simpler case.

**Comment by dai-shi** [comment]
Closing this as stale. Let's reopen when we have a repro.

**Comment by andreechristian** [comment]
Hi, @dai-shi , I am not able to create a proxy based on a Proxy.
Repro here: https://codesandbox.io/s/valtio-on-proxy-kerm0h?file=/src/index.ts

In my case, I would love to intercept the setter and store to local storage directly without needing to subscribe.

**Comment by dai-shi** [comment]
@andreechristian Thanks for the reproduction.
So, you can make a valtio proxy from another proxy, but it doesn't work as expected, right?
Unfortunately, it's the current design. `proxy(initialObject)` function copies `initialObject` to create a valtio proxy.
In the future version, we may revisit this "copying" behavior, but for now, it's how it is designed.

**Comment by andreechristian** [comment]
Noted. Thank you for getting back to me so quickly. Are there any reasons why we are copying instead of just using the original object?

**Comment by dai-shi** [comment]
To keep the original object unmodified. It can then be reused. (But, I notice this usage isn't very common.)
You can use frozen object too, thanks to copying.
