### ISSUE TITLE
Can't get the updated property from a class

### ISSUE THREAD

**Issue by la55u** [pmndrs/valtio#351]
What I'm trying to do is to subscribe to the changes of House class and run the validator service each time it changes.

Expected result:
the validator should log `size: 4`

Actual result:
the validator logs `size: 2`

Sandbox:
https://stackblitz.com/edit/typescript-xdujv5?devtoolsheight=33&file=index.ts

I made a similar example to demostrate it without valtio. It works as expected, but I can't use this in a real app because I would like to subscribe to a complex set of class instances that needs to be validated each time any of it's properties change.
The reason I'm using valtio for this problem is because there is a React presentational layer that also changes when the store changes. So the store (and snapshot) holds the right value but the validator class does not. 

Sandbox without valtio:
https://stackblitz.com/edit/typescript-fhcmcu?devtoolsheight=33&file=index.ts

Any help would be appreciated. Thank you

**Comment by DennisSmolek** [comment]
So I'm not entirely sure of the better pattern but what's happening is in your constructor you are adding the **ORIGINAL UNWRAPPED** object to the ValidatorService's internal Cache.

Later you're changing properties to the `store` which is essentially a clone of that object
`ValidatorService.objs[{id:''hh}] != store.h`

Here's my annoying level of consoles to see the order/highlights of what's happening
https://stackblitz.com/edit/typescript-kjv2nz

I tried some fixes,

Here's me adding the object after the constructor and with the correct reference to the store path:
https://stackblitz.com/edit/typescript-razm95

Works like the TS example.

So something this made me learn is that you cant refer to an object's global reference within the constructor, only the `this` property seems to work

```javascript
class House {
    const id: string;
    constructor(id) {
        this.id = id;
        const obj = store[id] // Undefined
}
const id = 'h';
store[id] = new House(id);
````

Unless I'm doing something wrong..

Anyway, I played with it a bit, moved some stuff around and came up with this:
https://stackblitz.com/edit/typescript-b6alzc?devtoolsheight=33&file=index.ts

Instead of passing the object reference I pass the ID and after the constructor add it to the `validatorService` as you did before. 

Not sure it's feasible in your actual use-case but in the example it works and its HIGHLY unlikely that you'll be firing changes that fast, if so I'd add your own `init()` method to the class and that's where you'll add it to the validator. It will be after the constructor and the `store[id]` reference should work

**Comment by la55u** [comment]
Thank you for the detailed answer, it was very helpful. However, the problem in my use-case is in your last example on line 21: `const obj = store[id]`. I can't add an object like this because I don't know in advance how to find it in the store. (Imagine the house has walls, the walls has windows, window has handles etc., all dynamic, everything can be added /removed. and everything has to be validated.) How would you approach the problem in this case?

In the meantime I also found a workaround:
https://stackblitz.com/edit/typescript-7qjpx1?devtoolsheight=33&file=index.ts
I simply added the validator instance to the store and it seems to work. Do you see any pitfalls with this approach? Thanks

**Comment by DennisSmolek** [comment]
> I simply added the validator instance to the store and it seems to work. Do you see any pitfalls with this approach? Thanks
🤦‍♂️
I'm annoyed I didn't think of that lol
Thats a much better/straightforward solution if you're able to do it, I'm still struggling how well Valtio wraps EVERYTHING with proxies and stuff just *MAGICALLY* works sometimes.

Yes, putting your validator service into the store and in your constructor referring to the `store.validator` is probably the fastest way to resolve it.



> I can't add an object like this because I don't know in advance how to find it in the store.

How are you storing the objects currently Is it as giant global object? Parent/Child Graph? etc? Are they just all on the global scope or do you have a service to wrap it?

It sounds crazy but you can probably just wrap the whole service in a `proxy` getters, setters, and all

If you dont have a schema/setup for that, I'd recommend either an `items` array in the store, where it's trivial to use `store.items.find(item => item.id == id)` or if it's a key/val object or map: store.items[key]
I wouldn't create the items on the global scope anyway and you can build in methods to your items to find themselves if not something as basic as `store.items[key] = new House(key)`
