### ISSUE TITLE
proxyWithComputed getter function return promise can't render as expect

### ISSUE THREAD

**Issue by ahaoboy** [pmndrs/valtio#484]
When proxyWithComputed getter function return promise App will infinite loop

store.ts
```ts
const store = proxyWithComputed(
  {
    count: 1,
  },
  {
    double(s) {
      return s.count * 2;
    },
    async doubledAsync(s) {
      return s.count * 2;
    },
  }
);
```

App.ts
```ts
function A() {
  const { count } = useSnapshot(store);
  console.log('A');
  return (
    <div>
      <h2>count:{count}</h2>
    </div>
  );
}
function B() {
  const { double } = useSnapshot(store);
  console.log('B');
  return (
    <div>
      <h2>double:{double}</h2>
    </div>
  );
}
function C() {
  const { doubledAsync } = useSnapshot(store);
  console.log('C');
  return (
    <div>
      <h2>doubledAsync:{doubledAsync}</h2>
    </div>
  );
}
function App() {
  return (
    <Suspense fallback="loading">
      <div>
        <A></A>
        <B></B>
        <C></C>
        <button onClick={() => store.count++}>inc count</button>
      </div>
    </Suspense>
  );
}
```

[demo](https://stackblitz.com/edit/vitejs-vite-r4kfwx?file=src%2Fmain.tsx,src%2FApp.tsx&terminal=dev)

**Comment by dai-shi** [comment]
`proxyWithComputed` is not designed to be work with promise/suspense.

`derive` would work better.
https://stackblitz.com/edit/vitejs-vite-wfm1nv?file=src%2Fmain.tsx,src%2FApp.tsx&terminal=dev

This is due to the proxyWithComputed implementation using object getters. We deal promise for suspense in proxy setter.
I don't think this is very easy to support without re-architecturing entire promise handling.

proxyWithComputed's computed properties are lazily evaluated, so using async props for suspense is not best practice anyway. So, I hesitate supporting it even if possible.

Closing this as won't fix for now.

I think we should basically recommend using `derive` in docs, and mark `proxyWithComputed` for expert use cases or even hide it somewhere.
